import type { Metadata } from "next";
import { AuthProvider } from './Providers';
import { SelectedItemsProvider } from './context/SelectedItemsContext'
import { Outfit } from 'next/font/google';
import "./globals.css";
const outfit = Outfit({ subsets: ['latin'], weight: ['100', '400', '700', '900'] });


export const metadata: Metadata = {
  title: "BhutanBookingHub",
  description: "Generated by create next app",
  icons:{
    icon:'/logo.jpg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head> 
      </head>
      <body className={outfit.className}>
     
        <SelectedItemsProvider>
          <AuthProvider>
            {children}
            {/* <Footer />  Include Footer for consistency */}
          </AuthProvider>
          </SelectedItemsProvider>
      </body>
    </html>
  );
}
